name: Publish to GitHub Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Set the Node.js version you need
          registry-url: https://npm.pkg.github.com/

      # Authenticate to GitHub Registry
      - name: Authenticate to GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Stage and commit any changes
      - name: Stage package-lock.json
        run: git add package-lock.json

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -m "fix: commit package-lock.json changes" || echo "No changes to commit"

      # Run Lerna version
      - name: Lerna version
        run: npx lerna version minor --yes

      # Build the project
      - name: Build the project
        run: npm run rollup

      # Publish the package to GitHub Package Registry
      - name: Publish to GitHub Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
